name: Build Padavan For test

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive|
      run: |
      
    - name: Set up Go ^1.17
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go  
    - name: Set Golang
      run: |
        cd /opt/hostedtoolcache/go
        rm -rf /opt/hostedtoolcache/go/1.15.15
        ls /opt/hostedtoolcache/go/
        ln -s ^1.17 1.15.15
        echo "new"
        ls /opt/hostedtoolcache/go/
